### ISSUE TITLE
Feature request for notifications - notification type

### ISSUE THREAD

**Issue by mylastore** [stephane-vanraes/renderless-svelte#23]
How can I pass something like this: notifications.push(err.message, 'warning') to support notification type?

**Comment by mylastore** [comment]
Figure this out this is what I did: 
usage: `notifications.push(err.message, 'warning')`
notifications store: 
```		const push = (message, messageType) =>
			update((arr) => [...arr, {message, messageType}]
		)
```
and on the implementation
```
		<Notification let:payload duration="10000">
			<p>Message Type: {payload.messageType}</p>
			<span>{payload.message}</span>
		</Notification>
``` 
Now I have message type example, success, warning, danger, success, info etc.

**Comment by stephane-vanraes** [comment]
The values passed into the notifications array can be anything, the docs page only has a string as an example, but (as you seem to have figured out) you can indeed do:

```js
import { notifications } from 'renderless-svelte';
notifications.push({ type: 'warning', text: 'This is a warning' });
```

I will have a look at making the documentation more explicit on this :)
